In [1]:
import numpy as np

In [13]:
X = np.random.randint(0, 10, (10, 3))

In [14]:
XXt = X.dot(X.T)

In [15]:
eigVals, eigVecs = np.linalg.eig(XXt)
eigValsIndices = eigVals.argsort()


In [19]:
eigValsIndices

array([3, 7, 6, 8, 9, 5, 4, 2, 1, 0])

In [22]:
eigValsIndices = eigValsIndices[:-3:-1]

In [23]:
eigVals

array([  8.54173420e+02 +0.00000000e+00j,
         1.01332945e+02 +0.00000000e+00j,
         6.64936354e+01 +0.00000000e+00j,
        -4.33857741e-14 +0.00000000e+00j,
         1.23812381e-14 +4.69926005e-15j,
         1.23812381e-14 -4.69926005e-15j,
        -4.01756745e-15 +8.67758846e-15j,
        -4.01756745e-15 -8.67758846e-15j,
        -2.69588189e-15 +0.00000000e+00j,   2.02267113e-15 +0.00000000e+00j])

In [24]:
U = eigVecs[:, eigValsIndices]

In [25]:
U

array([[ 0.18723896+0.j,  0.25285278+0.j],
       [-0.50011632+0.j,  0.27028291+0.j],
       [ 0.06263949+0.j,  0.41450369+0.j],
       [-0.53057684+0.j,  0.25119143+0.j],
       [-0.07438622+0.j,  0.27964501+0.j],
       [ 0.24330675+0.j,  0.39014237+0.j],
       [ 0.05569041+0.j,  0.37470013+0.j],
       [-0.14710959+0.j,  0.30076512+0.j],
       [ 0.57793946+0.j,  0.20271356+0.j],
       [ 0.07682183+0.j,  0.35459434+0.j]])

In [26]:
S = np.mat(np.diag(np.sqrt(eigVals[eigValsIndices])))

In [28]:
XtX = X.T.dot(X)
eigVals, eigVecs = np.linalg.eig(XtX)
eigValsIndices = eigVals.argsort()
eigValsIndices = eigValsIndices[:-3:-1]
V = eigVecs[:, eigValsIndices]

In [29]:
V

array([[ 0.55797225,  0.30662856],
       [ 0.63498108, -0.75602257],
       [ 0.53429018,  0.57828089]])

In [31]:
1+3j - 6

(-5+3j)

In [32]:
a = np.random.randint(0, 5, 5)

In [33]:
a

array([1, 0, 4, 0, 3])

In [34]:
a.argsort()

array([1, 3, 0, 4, 2])

In [42]:
a[:-3:-1]

array([3, 0])