In [1]:
import numpy as np

In [13]:
X = np.random.randint(0, 10, (10, 3))

In [14]:
XXt = X.dot(X.T)

In [15]:
eigVals, eigVecs = np.linalg.eig(XXt)
eigValsIndices = eigVals.argsort()


In [19]:
eigValsIndices

array([3, 7, 6, 8, 9, 5, 4, 2, 1, 0])

In [22]:
eigValsIndices = eigValsIndices[:-3:-1]

In [23]:
eigVals

array([  8.54173420e+02 +0.00000000e+00j,
         1.01332945e+02 +0.00000000e+00j,
         6.64936354e+01 +0.00000000e+00j,
        -4.33857741e-14 +0.00000000e+00j,
         1.23812381e-14 +4.69926005e-15j,
         1.23812381e-14 -4.69926005e-15j,
        -4.01756745e-15 +8.67758846e-15j,
        -4.01756745e-15 -8.67758846e-15j,
        -2.69588189e-15 +0.00000000e+00j,   2.02267113e-15 +0.00000000e+00j])

In [24]:
U = eigVecs[:, eigValsIndices]

In [25]:
U

array([[ 0.18723896+0.j,  0.25285278+0.j],
       [-0.50011632+0.j,  0.27028291+0.j],
       [ 0.06263949+0.j,  0.41450369+0.j],
       [-0.53057684+0.j,  0.25119143+0.j],
       [-0.07438622+0.j,  0.27964501+0.j],
       [ 0.24330675+0.j,  0.39014237+0.j],
       [ 0.05569041+0.j,  0.37470013+0.j],
       [-0.14710959+0.j,  0.30076512+0.j],
       [ 0.57793946+0.j,  0.20271356+0.j],
       [ 0.07682183+0.j,  0.35459434+0.j]])

In [26]:
S = np.mat(np.diag(np.sqrt(eigVals[eigValsIndices])))

In [28]:
XtX = X.T.dot(X)
eigVals, eigVecs = np.linalg.eig(XtX)
eigValsIndices = eigVals.argsort()
eigValsIndices = eigValsIndices[:-3:-1]
V = eigVecs[:, eigValsIndices]

In [29]:
V

array([[ 0.55797225,  0.30662856],
       [ 0.63498108, -0.75602257],
       [ 0.53429018,  0.57828089]])

In [31]:
1+3j - 6

(-5+3j)

In [32]:
a = np.random.randint(0, 5, 5)

In [33]:
a

array([1, 0, 4, 0, 3])

In [34]:
a.argsort()

array([1, 3, 0, 4, 2])

In [42]:
a[:-3:-1]

array([3, 0])

In [2]:
# analyze the NG20 dataset using the class sklearn LDA using 10 topics
from __future__ import  print_function
from time import time

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.datasets import fetch_20newsgroups
from sklearn.datasets import f

In [10]:
n_sampes = 2000
n_features = 1000
n_topics = 20
n_top_words = 10

In [11]:
def print_top_words(model, feature_names, n_top_words):
    for topic_idx, topic in enumerate(model.components_):
        print('Topic #%d' % topic_idx)
        print(' '.join([feature_names[i] for i in topic.argsort()[:-n_top_words - 1:-1]]))
    
    print()

In [12]:
print('load dataset')
t0 = time()
dataset = fetch_20newsgroups(shuffle=True, random_state=1, remove=('headers', 'footers', 'quotes'))
data_samples = dataset.data
print('done in %0.3fs' % (time() - t0))

load dataset
done in 1.024s


In [13]:
# use tf (raw term count) features for LDA
print('extracting tf features for LDA')
tf_vectorizer = CountVectorizer(max_df=0.95, min_df=2, max_features=n_features, stop_words='english')
t0 = time()
tf = tf_vectorizer.fit_transform(data_samples)
print('done in %0.3fs' % (time() - t0))

extracting tf features for LDA
done in 1.320s


In [14]:
print('fitting LDA models with tf features, n_sampes=%d and n_features=%d' % (n_sampes, n_features))
lda = LatentDirichletAllocation(n_topics=n_topics, max_iter=5, learning_method='online', learning_offset=50., random_state=0)
t0 = time()
lda.fit(tf)
print('done in %0.3fs' % (time() - t0))

fitting LDA models with tf features, n_sampes=2000 and n_features=1000


/users/master/ij10268/miniconda3/lib/python3.6/site-packages/sklearn/decomposition/online_lda.py:294: DeprecationWarning: n_topics has been renamed to n_components in version 0.19 and will be removed in 0.21
  DeprecationWarning)


done in 13.892s


In [15]:
print('topics in LDA model:')
tf_feature_names = tf_vectorizer.get_feature_names()
print_top_words(lda, tf_feature_names, n_top_words)

topics in LDA model:
Topic #0
people gun state control right guns crime states law police
Topic #1
time question book years did like don space answer just
Topic #2
mr line rules science stephanopoulos title current define int yes
Topic #3
key chip keys clipper encryption number des algorithm use bit
Topic #4
edu com cs vs w7 cx mail uk 17 send
Topic #5
use does window problem way used point different case value
Topic #6
windows thanks know help db does dos problem like using
Topic #7
bike water effect road design media dod paper like turn
Topic #8
don just like think know people good ve going say
Topic #9
car new price good power used air sale offer ground
Topic #10
file available program edu ftp information files use image version
Topic #11
ax max b8f g9v a86 145 pl 1d9 0t 34u
Topic #12
government law privacy security legal encryption court fbi technology information
Topic #13
card bit memory output video color data mode monitor 16
Topic #14
drive scsi disk mac hard apple drives contr